name: CI
on: 
  push:
    tags: 
      - release/*
    branches:
      - master

jobs:

  publish_package_branch:
    runs-on: ubuntu-latest
    steps:
    - name: split subtree
      run:
        echo "Splitting subtree"
        new_assets_head=`git subtree split --prefix Assets HEAD`
        echo "Subtree split successful. Commit = $new_assets_head"
        git branch -f master-assets $new_assets_head
        
        
        git checkout master-assets
        git push
        # TODO: replace with pushing specific branch to specific upstream
