name: CI
on: 
  push:
    # TODO: uncomment
#     tags: 
#       - release/*
    branches:
      - master

jobs:

  publish_package_branch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Repository name with owner. For example, actions/checkout
        # Default: ${{ github.repository }}
        repository: ''

        # The branch, tag or SHA to checkout. When checking out the repository that
        # triggered a workflow, this defaults to the reference or SHA for that event.
        # Otherwise, defaults to `master`.
        ref: ''

        # Auth token used to fetch the repository. The token is stored in the local git
        # config, which enables your scripts to run authenticated git commands. The
        # post-job step removes the token from the git config. [Learn more about creating
        # and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
        # Default: ${{ github.token }}
        token: ''

        # Whether to persist the token in the git config
        # Default: true
        persist-credentials: ''

        # Relative path under $GITHUB_WORKSPACE to place the repository
        path: ''

        # Whether to execute `git clean -ffdx && git reset --hard HEAD` before fetching
        # Default: true
        clean: ''

        # Number of commits to fetch. 0 indicates all history.
        # Default: 1
        fetch-depth: ''

        # Whether to download Git-LFS files
        # Default: false
        lfs: true
    - name: split subtree
      run:
        echo "Splitting subtree"
        new_assets_head=`git subtree split --prefix Assets HEAD`
        echo "Subtree split successful. Commit = $new_assets_head"
        git branch -f master-assets $new_assets_head
        
        
        git checkout master-assets
        git push
        # TODO: replace with pushing specific branch to specific upstream
